version: '3'
networks:
  laravel:
services:

  # Webserver Image
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  # Database Image
  mysql:
    platform: linux/amd64
    image: mysql:5.7.34
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: gumbo_shrimp
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # Backend Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: $HOST_UID
    container_name: php
    volumes:
      - ./:/var/www
    networks:
      - laravel
    # depends_on:
    #   mysql:
    #     condition: service_healthy

# Volumes
volumes:
  mysqldata: